create table if not exists customer
(
    id               bigint generated by default as identity
    constraint pk_customer primary key,

    first_name       varchar(100) not null,
    last_name        varchar(100) not null,

    email            varchar(255) not null
    constraint uk_customer_email unique,
    password         varchar(255) not null,

    street           varchar(50)  not null,
    city             varchar(50)  not null,
    state_province   varchar(20)  not null,
    postal_code      varchar(20)  not null,
    country          varchar(50)  not null,

    type             varchar(10)  not null,
    number           varchar(20)  not null,
    expiration_month integer      not null,
    expiration_year  integer      not null
    );

create table if not exists salesorder
(
    id               bigint generated by default as identity
    constraint pk_salesorder primary key,

    date             timestamp      not null,
    status           varchar(20),
    amount           numeric(19, 2) not null,

    street           varchar(50)    not null,
    city             varchar(50)    not null,
    state_province   varchar(20)    not null,
    postal_code      varchar(20)    not null,
    country          varchar(50)    not null,

    type             varchar(10)    not null,
    number           varchar(20)    not null,
    expiration_month integer        not null,
    expiration_year  integer        not null,

    customer_id      bigint         not null
    constraint fk_salesorder_customer references customer
    );

create table if not exists order_item
(
    id       bigint generated by default as identity
    constraint pk_order_item primary key,

    isbn     varchar(13),
    title    varchar(200),
    authors  varchar(200),
    price    numeric(7, 2),

    quantity integer not null,

    order_id bigint
    constraint fk_order_item_salesorder references salesorder
    );
